-- MySQL Script generated by MySQL Workbench
-- Fri Jun 19 16:36:52 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema monitoramento_indoor
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `tb_dispositivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_dispositivo` (
  `id_dispositivo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `no_localizacao` VARCHAR(45) NOT NULL,
  `no_dispositivo` VARCHAR(15) NOT NULL,
  `vl_min_luminosidade` INT(3) NOT NULL,
  PRIMARY KEY (`id_dispositivo`),
  UNIQUE INDEX `id_dispositivo_UNIQUE` (`id_dispositivo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tb_ocorrencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_ocorrencia` (
  `id_ocorrencia` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_dispositivo` INT UNSIGNED NOT NULL,
  `vl_temperatura` DECIMAL(3,1) NOT NULL,
  `vl_luminosidade` INT(3) NOT NULL,
  `dt_ocorrencia` DATE NOT NULL,
  `hr_ocorrencia` TIME NOT NULL,
  `st_luminosidade` CHAR(1) NOT NULL,
  PRIMARY KEY (`id_ocorrencia`),
  UNIQUE INDEX `idtb_luminosidade_UNIQUE` (`id_ocorrencia` ASC),
  INDEX `fk_tb_ocorrencia_tb_dispositivo_idx` (`id_dispositivo` ASC),
  CONSTRAINT `fk_tb_ocorrencia_tb_dispositivo`
    FOREIGN KEY (`id_dispositivo`)
    REFERENCES `tb_dispositivo` (`id_dispositivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tmp_ocorrencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tmp_ocorrencia` (
  `id_tmp_ocorrencia` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_ocorrencia` INT UNSIGNED NOT NULL,
  `id_dispositivo` INT NOT NULL,
  `vl_temperatura` DECIMAL(3,1) NOT NULL,
  `vl_luminosidade` INT(3) NOT NULL,
  `dt_ocorrencia` DATE NOT NULL,
  `hr_ocorrencia` TIME NOT NULL,
  `st_luminosidade` CHAR(1) NOT NULL,
  PRIMARY KEY (`id_tmp_ocorrencia`),
  UNIQUE INDEX `id_tmp_ocorrencia_UNIQUE` (`id_tmp_ocorrencia` ASC),
  INDEX `fk_tmp_ocorrencia_tb_ocorrencia1_idx` (`id_ocorrencia` ASC),
  CONSTRAINT `fk_tmp_ocorrencia_tb_ocorrencia1`
    FOREIGN KEY (`id_ocorrencia`)
    REFERENCES `tb_ocorrencia` (`id_ocorrencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tb_historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_historico` (
  `id_historico` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_dispositivo` INT UNSIGNED NOT NULL,
  `vl_media_disp` DECIMAL(3,1) NOT NULL,
  `vl_qtde_disp` INT NOT NULL,
  `dt_geracao` DATE NOT NULL,
  `hr_geracao` TIME NOT NULL,
  PRIMARY KEY (`id_historico`),
  UNIQUE INDEX `id_tmp_consolidado_UNIQUE` (`id_historico` ASC),
  INDEX `fk_tb_historico_tb_dispositivo1_idx` (`id_dispositivo` ASC),
  CONSTRAINT `fk_tb_historico_tb_dispositivo1`
    FOREIGN KEY (`id_dispositivo`)
    REFERENCES `tb_dispositivo` (`id_dispositivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tb_parametro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_parametro` (
  `intervalo_min` INT NOT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
